functionsDirectory = "Z:\\Class Project\\Projects\\tailwind-css\\my-react-app\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "Z:\\Class Project\\Projects\\tailwind-css\\my-react-app\\dist"
publishOrigin = "config"
commandOrigin = "config"
base = "Z:\\Class Project\\Projects\\tailwind-css\\my-react-app"
command = "npm run dev"
functions = "Z:\\Class Project\\Projects\\tailwind-css\\my-react-app\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]