[build]
  base = "my-react-app"
  publish = "my-react-app/dist"
  command = "npm run build"

[functions]
  directory = "../netlify/functions"   # <-- important change

[dev]
  command = "npm run dev --prefix my-react-app"
  targetPort = 5173
  framework = "#custom"