[build]
  # already *in* my-react-app, so no base
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "../netlify/functions"   # go up to the root-level functions

[[redirects]]
  from = "/api/omdb"
  to = "/.netlify/functions/omdb"
  status = 200
  force = true

[[redirects]]
  from = "/api/weather"
  to = "/.netlify/functions/weather"
  status = 200
  force = true
